{% set version = "0.24.0" %}

package:
  name: atlasgo
  version: {{ version }}

source:
  url: https://github.com/ariga/atlas/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 33fc874bd5c155f7d1a88a36efd0a431bc4eaa41ca0602684bc7259538453f60

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}      # [unix]
    - {{ stdlib('c') }}        # [unix]
    - {{ compiler('go-cgo') }} >=1.21
    - go-licenses

test:
  commands:
    - atlas version
    - atlas --help

about:
  home: https://atlasgo.io
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: Manage your database schema as code
  doc_url: https://atlasgo.io/getting-started
  dev_url: https://github.com/ariga/atlas

extra:
  recipe-maintainers:
    - borchero
