{% set version = "0.33.1" %}

package:
  name: atlasgo
  version: {{ version }}

source:
  url: https://github.com/ariga/atlas/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 97fcaca965d7c49a5290d1bb84aaa996c8ca1d542b557e865952aa5c8bf94baf
  patches:
    # NOTE: Required to circumvent issues with the atlas SDK (cf. https://github.com/ariga/atlas-go-sdk/pull/66).
    - patches/001-remove-unofficial-string.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}      # [unix]
    - {{ stdlib('c') }}        # [unix]
    - {{ compiler('go-cgo') }} >=1.21
    - go-licenses

test:
  commands:
    - atlas version | grep "atlas version v{{ version }}"
    - atlas --help

about:
  home: https://atlasgo.io
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: Manage your database schema as code
  doc_url: https://atlasgo.io/getting-started
  dev_url: https://github.com/ariga/atlas

extra:
  recipe-maintainers:
    - borchero
