context:
  version: "1.2.0"

package:
  name: atlasgo
  version: ${{ version }}

source:
  url: https://github.com/ariga/atlas/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0968b685458da1f414d3a8d09fe7ee9a3359906fade36fe787369c40d757f2fe
  patches:
    # NOTE: Required to circumvent issues with the atlas SDK (cf. https://github.com/ariga/atlas-go-sdk/pull/66).

build:
  number: 0
  skip: ${{ win }}
  script:
    - cd cmd/atlas
    # NOTE: github.com/libsql/sqlite-antlr4-parser is generated and does not include a license.
    #       Licenses for ANTLR4 projects are already included for other dependencies.
    # Last ignore line is a workaround for https://github.com/google/go-licenses/issues/244
    - go-licenses save . --save_path ../../library_licenses --ignore ariga.io/atlas --ignore github.com/libsql/sqlite-antlr4-parser --ignore github.com/jmespath/go-jmespath --ignore $(go list std | awk 'NR > 1 { printf(",") } { printf("%s",$0) } END { print "" }')
    - go build -v -ldflags "-s -w -X 'ariga.io/atlas/cmd/atlas/internal/cmdapi.version=v$PKG_VERSION'" -o $PREFIX/bin/atlas

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }} >=1.26.1
    - go-licenses

tests:
  - script:
      - atlas version | grep "atlas version v${{ version }}"
      - atlas --help

about:
  homepage: https://atlasgo.io
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: Manage your database schema as code
  documentation: https://atlasgo.io/getting-started
  repository: https://github.com/ariga/atlas

extra:
  recipe-maintainers:
    - borchero
    - delsner
